allowBuilds:
  '@parcel/watcher': true
  simple-git-hooks: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - vite@8.2.0
  - alova@3.5.4
  - pinia@4.0.3
  - sass-embedded-all-unknown@1.102.0
  - sass-embedded-android-arm64@1.102.0
  - sass-embedded-android-arm@1.102.0
  - sass-embedded-android-riscv64@1.102.0
  - sass-embedded-android-x64@1.102.0
  - sass-embedded-darwin-arm64@1.102.0
  - sass-embedded-darwin-x64@1.102.0
  - sass-embedded-linux-arm64@1.102.0
  - sass-embedded-linux-arm@1.102.0
  - sass-embedded-linux-musl-arm64@1.102.0
  - sass-embedded-linux-musl-arm@1.102.0
  - sass-embedded-linux-musl-riscv64@1.102.0
  - sass-embedded-linux-musl-x64@1.102.0
  - sass-embedded-linux-riscv64@1.102.0
  - sass-embedded-linux-x64@1.102.0
  - sass-embedded-unknown-all@1.102.0
  - sass-embedded-win32-arm64@1.102.0
  - sass-embedded-win32-x64@1.102.0
  - sass-embedded@1.102.0
  - '@types/node@26.3.0'
  - eslint@10.9.1

shellEmulator: true

trustPolicy: no-downgrade

overrides:
  semver: ^7.8.5
